name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies and build (Frontend)
      run: |
        cd frontend
        npm ci
        npm run build --if-present
    - name: Install dependencies (Backend)
      run: |
        cd backend
        npm ci
    - name: Run tests (Frontend)
      run: |
        cd frontend
        npm test -- --passWithNoTests
    - name: Run tests (Backend)
      run: |
        cd backend
        npm test -- --passWithNoTests